sudo: false
language: node_js
node_js:
- '8'
os:
- osx
- linux
before_install:
- if [ $TRAVIS_OS_NAME == "linux" ]; then export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
  sh -e /etc/init.d/xvfb start; sleep 3; fi
- npm install -g typescript
install:
- npm install
- npm run compile
after_script:
- npm run coveralls
deploy:
  provider: npm
  email: gorkem.ercan@gmail.com
  skip_cleanup: true
  on:
    tags: true
    repo: redhat-developer/yaml-language-server
  api_key:
    secure: q5zN3WjUGWWTlxC0yViMK9RcXeEEwYRsXuqEwYBEyz+er4XUJzisHdXELu0tf56caCZ1Kp0NCUHsGqyV+fBS5zhaR0SSil59tSPp3fo+av/eLymI+4RXLAo3vCuRITSKPG+AwJnwAZF5cwGRdUCKPjV0yi7lX/WcZzZCPKb4IlKpMET/x9n0vhtSRK0Spxb0xB+pdjzujOHg2hkU9J81i1c62pZ6KlGhipdRrsONB6ujpSgpBakatp6FFPwmg8YwjbrNAWcqBZA1KwgiymaJSUa0asrGqeTRph/+xtVIr1WYRL7ed4yg1EYhLptNThhlO+To4FSZbOQfE5Rqcgo1BcLFLgQuPdp5HQwnQcVrkKWvRDyxvNI61cSW9Pb3hwytcVik0yz5neRGWVmJpVRulK5LVH37+XqVmic5Amc46ovst7HHw52dKayR97FoBq1+CXpxCONdjtvWnHZgahXxjOb4pJkNaGnmOR157MZ7Oo6GrilOSo8WBtdsOv2/CCrL119Eqbr8rJuQR9H2q5Y7at0QNsuO24jrKvFmqf8igE0t6Z70Dk1cxApME5nMAaww/tL7Mgv4zSvSGQRykwxvAZfoIu4v0fRHR+3I5wRy4P0HHvwxGlBPhq8+m4aCzHCbL+AejEOxSWknhnE/AEd9p719mVMx6FbqBrilnuSlOsg=
